/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabajoaccdatequipo1;

import static com.mycompany.trabajoaccdatequipo1.TrabajoAccDatEquipo1.interfaz;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class PromptsInterfaz extends javax.swing.JFrame {

    private int filaSeleccionada = -1; // -1 indica que no hay ninguna fila seleccionada inicialmente
    private List<Prompts> listPrompts = MetodosLucas.obtenerTodosLosPrompts();;
    
    /**
     * Creates new form PromptsInterfaz
     */
    public PromptsInterfaz() {
        initComponents();
        desactivarBotones();

        establecerTabla();
        cargarDatosEnTabla();
    }

    public void cargarDatosEnTabla(){
        
        DefaultTableModel modelo = (DefaultTableModel) tablaPrompts.getModel();
        
        modelo.setRowCount(0);
        
        for(Prompts p: listPrompts){
            String texto = p.getTexto();
            Object[] fila = new Object[]{texto};
            modelo.addRow(fila);
        }
    }
    
    public void desactivarBotones(){
        eliminarBoton.setEnabled(false);
        iasAsociadasBoton.setEnabled(false);
    }
    
    public void establecerTabla(){
        tablaPrompts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}, // Inicializa con dos columnas en lugar de cuatro
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Prompts" // Cambia los títulos de las columnas aquí
            }
        ));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jPanel1 = new javax.swing.JPanel();
        atrasBoton = new javax.swing.JButton();
        iasAsociadasBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        añadirBoton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPrompts = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Prompts"));

        atrasBoton.setText("Atrás");
        atrasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBotonActionPerformed(evt);
            }
        });

        iasAsociadasBoton.setText("Ver IAs asociadas");
        iasAsociadasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iasAsociadasBotonActionPerformed(evt);
            }
        });

        eliminarBoton.setText("Eliminar prompts");
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });

        añadirBoton.setText("Añadir prompts");

        tablaPrompts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPrompts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaPrompts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPromptsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPrompts);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atrasBoton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iasAsociadasBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eliminarBoton)
                                .addGap(159, 159, 159)
                                .addComponent(añadirBoton)))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iasAsociadasBoton)
                    .addComponent(eliminarBoton)
                    .addComponent(añadirBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atrasBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBotonActionPerformed
        dispose();
        interfaz();
    }//GEN-LAST:event_atrasBotonActionPerformed

    private void iasAsociadasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iasAsociadasBotonActionPerformed
        int filaSeleccionada = tablaPrompts.getSelectedRow();
        if (filaSeleccionada >= 0) { // Asegúrate de que hay una fila seleccionada
            filaSeleccionada = tablaPrompts.convertRowIndexToModel(filaSeleccionada);// Convierte a índice del modelo si es necesario
            
            Prompts p = listPrompts.get(filaSeleccionada);
            int idPrompt = p.getIdprompt();
            
            MostrarPromptsIAS ventanaIAs = new MostrarPromptsIAS(idPrompt);
            ventanaIAs.setVisible(true);
        }
    }//GEN-LAST:event_iasAsociadasBotonActionPerformed

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        int filaSeleccionada = tablaPrompts.getSelectedRow();
        if (filaSeleccionada >= 0) { // Asegúrate de que hay una fila seleccionada
            filaSeleccionada = tablaPrompts.convertRowIndexToModel(filaSeleccionada);// Convierte a índice del modelo si es necesario
            
            int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Estás seguro de que deseas eliminar este prompt?", "Confirmar eliminación", 
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            
            if (confirmacion == JOptionPane.YES_OPTION) {
            
                Prompts p = listPrompts.get(filaSeleccionada);
                int idPrompt = p.getIdprompt();

                MetodosLucas.borrarPrompt(filaSeleccionada);

                listPrompts.remove(filaSeleccionada);

                cargarDatosEnTabla();

                desactivarBotones();
                
            }
        }
    }//GEN-LAST:event_eliminarBotonActionPerformed

    private void tablaPromptsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPromptsMouseClicked
        int filaSeleccionada = tablaPrompts.getSelectedRow();
        
        eliminarBoton.setEnabled(true);
        iasAsociadasBoton.setEnabled(true);
    }//GEN-LAST:event_tablaPromptsMouseClicked

    private void abrirVentanaModificar() {
        // Asume que tu ventana principal se extiende de JFrame
        ModificarPromptsInterfaz ventanaModificar = new ModificarPromptsInterfaz();
        ventanaModificar.setLocationRelativeTo(this); // Para centrar respecto a la ventana principal
        ventanaModificar.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromptsInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromptsInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromptsInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromptsInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromptsInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBoton;
    private javax.swing.JButton añadirBoton;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JButton iasAsociadasBoton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTable tablaPrompts;
    // End of variables declaration//GEN-END:variables
}
